### ISSUE TITLE
Bug: Inconsistent TNT behavior when falling over 3 blocks on blue aerclouds.

### ISSUE THREAD

**Issue by MelonVision** [The-Aether-Team/The-Aether-Genesis#169] opened 2023-06-27 01:28 UTC
### What Feature Types Apply to This Bug?

Block, Entity

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

45.0.64

### The Aether Genesis Version

beta5 latest

### Is This Bug a Conflict With Another Mod?

No

### Steps to Reproduce

Happens consistently when tnt falls on aerclouds.
1. Place a blue aercloud and pillar 3 blocks.
2. place tnt and break the three blocks beneath it.
3. Light the tnt. It should bounce on the aercloud.
4. make a similar pillar but but have a 4 block gap.
5. light the tnt and it should sink into the block.

### What You Expect To Happen

Tnt to behave consistently regardless of drop height.

### What Actually Happened

TNT that falls over 4 blocks gets stuck in the aercloud probably due to moving too fast.

### Additional Details

Video: https://www.youtube.com/watch?v=i211Bij1WyA

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment] 2023-06-27 06:03
Duplicate of an issue on the Aether repo

**Closed as completed by bconlon1** 2023-06-27 06:03 UTC
Labels: type/bug
